'use strict';
const ip=require('ip');
const ZooKeeper = require('node-zookeeper-client');
//var fs = require('fs');

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  throw err;
});

// Ensure environment variables are read.
require('../config/env');


const fs = require('fs');
const chalk = require('chalk');
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const clearConsole = require('react-dev-utils/clearConsole');
const checkRequiredFiles = require('react-dev-utils/checkRequiredFiles');
const {
  choosePort,
  createCompiler,
  prepareProxy,
  prepareUrls,
} = require('react-dev-utils/WebpackDevServerUtils');
const openBrowser = require('react-dev-utils/openBrowser');
const paths = require('../config/paths');
const configFactory = require('../config/webpack.config');
const createDevServerConfig = require('../config/webpackDevServer.config');

const useYarn = fs.existsSync(paths.yarnLockFile);
const isInteractive = process.stdout.isTTY;

//const serverUrl=require("../src/static/Config/Config")
// Warn and crash if required files are missing
if (!checkRequiredFiles([paths.appHtml, paths.appIndexJs])) {
  process.exit(1);
}

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000;
const HOST = process.env.HOST || '0.0.0.0';

if (process.env.HOST) {
  console.log(
    chalk.cyan(
      `Attempting to bind to HOST environment variable: ${chalk.yellow(
        chalk.bold(process.env.HOST)
      )}`
    )
  );
  console.log(
    `If this was unintentional, check that you haven't mistakenly set it in your shell.`
  );
  console.log(
    `Learn more here: ${chalk.yellow('http://bit.ly/CRA-advanced-config')}`
  );
  console.log();
}

// We require that you explictly set browsers and do not fall back to
// browserslist defaults.
const { checkBrowsers } = require('react-dev-utils/browsersHelper');
checkBrowsers(paths.appPath, isInteractive)
  .then(() => {
    // We attempt to use the default port but if it is busy, we offer the user to
    // run on a different port. `choosePort()` Promise resolves to the next free port.
    return choosePort(HOST, DEFAULT_PORT);
  })
  .then(port => {
    if (port == null) {
      // We have not found a port.
      return;
    }
    const env = process.env;
    const config = configFactory('development');
    const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
    const appName = require(paths.appPackageJson).name;
    const urls = prepareUrls(protocol, HOST, port);
    // Create a webpack compiler that is configured with custom messages.
    const compiler = createCompiler(webpack, config, appName, urls, useYarn);
    // Load proxy config
    const proxySetting = require(paths.appPackageJson).proxy;
    const proxyConfig = prepareProxy(proxySetting, paths.appPublic);
    // Serve webpack assets generated by the compiler over a web server.
    const serverConfig = createDevServerConfig(
      proxyConfig,
      urls.lanUrlForConfig
    );
    const devServer = new WebpackDevServer(compiler, serverConfig);

    // Launch WebpackDevServer.
    devServer.listen(port, HOST, err => {
      if (err) {
        return console.log(err);
      }
      if (isInteractive) {
        clearConsole();
      }
      console.log(chalk.cyan('Starting the development server...\n'));
      
      console.log("Start *************")
      client.connect();
      
      checkNodeExists("/ensemble/apiServer")
      .then(doesExist=>{
        return getZnodeData("/ensemble/apiServer")
      })
      .then(data=>{
        var stream = fs.createWriteStream("src/static/Config/Config.js");

        stream.once('open', (fd) => {
        stream.write("const SERVER_URL=\"http://"+data+"\";\n");
        stream.write("export default SERVER_URL;\n");

        // Important to close the stream when you're ready
        stream.end();
});
      //  console.log("Here ..."+ process.env)
      //  process.env.connectionString="http://"+data
     //   console.log(process.env.connectionString)
       // localStorage.setItem(process.env.connectionString);
      })
      .catch(error=>{
        console.log("API server is not up!!")
        process.exit();
      });

      openBrowser(urls.localUrlForBrowser);
    });

    ['SIGINT', 'SIGTERM'].forEach(function(sig) {
      process.on(sig, function() {
        devServer.close();
        process.exit();
      });
    });
  })
  .catch(err => {
    if (err && err.message) {
      console.log(err.message);
    }
    process.exit(1);
  });



  console.log("Search component did mount")
  const client = ZooKeeper.createClient('149.165.171.39:2181',{ sessionTimeout: 5000 });
  console.log("here")
  console.log(client)
  client.once('connected', function () {
     console.log('Connected to the server.');
  
     client.create("/ensemble/uiModule",new Buffer(ip.address() +":4000"),ZooKeeper.CreateMode.EPHEMERAL, function (error) {
         if (error) {
             console.log('Failed to create node: %s due to: %s.', error);
         } else {
             console.log('Node: %s is successfully created.');
         }
  
         //client.close();
     });
 });

 const checkNodeExists=(path)=>{
  const zookeeperClient=client;
  return new Promise((resolve,reject)=>{
      zookeeperClient.exists(path,function (error, stat) {
          if (error) {
              reject(false)
          }
          if (stat) {
              resolve(true)
          } else {
              reject(false)
          }})
  })
  

}

const getZnodeData=(path)=>{
  const zookeeperClient=client;
  console.log(zookeeperClient);
  return new Promise((resolve,reject)=>{
      zookeeperClient.getData(
          path,
          function (event) {
              console.log('Got event: %s.', event);
          },
          function (error, data, stat) {
              if (error) {
                  console.log(error.stack);
                  reject(error.stack)
              }
              console.log('Got data: %s', data.toString('utf8'));
              resolve(data.toString('utf8'))          
          }
      );
  })
 
}
// client.connect();